#![allow(non_camel_case_types)]

use chrono_tz::Tz;
use std::i32;

/// Time Metazones list.
///
/// Metazones are the timezones as usually named (e.g. “Central Mountain Time”).
/// They group the city-based timezones in non-obvious ways.
#[derive(Copy,Clone,Debug,PartialEq,Eq,Hash,PartialOrd,Ord)]
pub enum MetaZone {
    Unknown,
    Acre,
    Afghanistan,
    Africa_Central,
    Africa_Eastern,
    Africa_FarWestern,
    Africa_Southern,
    Africa_Western,
    Aktyubinsk,
    Alaska,
    Alaska_Hawaii,
    Almaty,
    Amazon,
    America_Central,
    America_Eastern,
    America_Mountain,
    America_Pacific,
    Anadyr,
    Apia,
    Aqtau,
    Aqtobe,
    Arabian,
    Argentina,
    Argentina_Western,
    Armenia,
    Ashkhabad,
    Atlantic,
    Australia_Central,
    Australia_CentralWestern,
    Australia_Eastern,
    Australia_Western,
    Azerbaijan,
    Azores,
    Baku,
    Bangladesh,
    Bering,
    Bhutan,
    Bolivia,
    Borneo,
    Brasilia,
    British,
    Brunei,
    Cape_Verde,
    Casey,
    Chamorro,
    Chatham,
    Chile,
    China,
    Choibalsan,
    Christmas,
    Cocos,
    Colombia,
    Cook,
    Cuba,
    Dacca,
    Davis,
    Dominican,
    DumontDUrville,
    Dushanbe,
    Dutch_Guiana,
    East_Timor,
    Easter,
    Ecuador,
    Europe_Central,
    Europe_Eastern,
    Europe_Further_Eastern,
    Europe_Western,
    Falkland,
    Fiji,
    French_Guiana,
    French_Southern,
    Frunze,
    GMT,
    Galapagos,
    Gambier,
    Georgia,
    Gilbert_Islands,
    Goose_Bay,
    Greenland_Central,
    Greenland_Eastern,
    Greenland_Western,
    Guam,
    Gulf,
    Guyana,
    Hawaii_Aleutian,
    Hong_Kong,
    Hovd,
    India,
    Indian_Ocean,
    Indochina,
    Indonesia_Central,
    Indonesia_Eastern,
    Indonesia_Western,
    Iran,
    Irish,
    Irkutsk,
    Israel,
    Japan,
    Kamchatka,
    Karachi,
    Kazakhstan_Eastern,
    Kazakhstan_Western,
    Kizilorda,
    Korea,
    Kosrae,
    Krasnoyarsk,
    Kuybyshev,
    Kwajalein,
    Kyrgystan,
    Lanka,
    Liberia,
    Line_Islands,
    Lord_Howe,
    Macau,
    Macquarie,
    Magadan,
    Malaya,
    Malaysia,
    Maldives,
    Marquesas,
    Marshall_Islands,
    Mauritius,
    Mawson,
    Mexico_Northwest,
    Mexico_Pacific,
    Mongolia,
    Moscow,
    Myanmar,
    Nauru,
    Nepal,
    New_Caledonia,
    New_Zealand,
    Newfoundland,
    Niue,
    Norfolk,
    Noronha,
    North_Mariana,
    Novosibirsk,
    Omsk,
    Oral,
    Pakistan,
    Palau,
    Papua_New_Guinea,
    Paraguay,
    Peru,
    Philippines,
    Phoenix_Islands,
    Pierre_Miquelon,
    Pitcairn,
    Ponape,
    Pyongyang,
    Qyzylorda,
    Reunion,
    Rothera,
    Sakhalin,
    Samara,
    Samarkand,
    Samoa,
    Seychelles,
    Shevchenko,
    Singapore,
    Solomon,
    South_Georgia,
    Suriname,
    Sverdlovsk,
    Syowa,
    Tahiti,
    Taipei,
    Tajikistan,
    Tashkent,
    Tbilisi,
    Tokelau,
    Tonga,
    Truk,
    Turkey,
    Turkmenistan,
    Tuvalu,
    Uralsk,
    Uruguay,
    Urumqi,
    Uzbekistan,
    Vanuatu,
    Venezuela,
    Vladivostok,
    Volgograd,
    Vostok,
    Wake,
    Wallis,
    Yakutsk,
    Yekaterinburg,
    Yerevan,
    Yukon,
}

#[derive(Copy,Clone,Debug,PartialEq,Eq,Hash,PartialOrd,Ord)]
pub struct UnixMinute(i32);

/// TimeZone -> Metazone mapping
pub static TIME_ZONE_MAP : &[(Tz, UnixMinute, UnixMinute, MetaZone)] = &[
    (Tz::Africa__Abidjan, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::GMT),
    (Tz::Africa__Accra, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::GMT),
    (Tz::Africa__Addis_Ababa, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Africa_Eastern),
    (Tz::Africa__Algiers, UnixMinute(i32::MIN), UnixMinute(4103940), MetaZone::Europe_Western),
    (Tz::Africa__Algiers, UnixMinute(4103940), UnixMinute(5162340), MetaZone::Europe_Central),
    (Tz::Africa__Algiers, UnixMinute(5162340), UnixMinute(5958720), MetaZone::Europe_Western),
    (Tz::Africa__Algiers, UnixMinute(5958720), UnixMinute(i32::MAX), MetaZone::Europe_Central),
    (Tz::Africa__Asmera, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Africa_Eastern),
    (Tz::Africa__Bamako, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::GMT),
    (Tz::Africa__Bangui, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Africa_Western),
    (Tz::Africa__Banjul, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::GMT),
    (Tz::Africa__Bissau, UnixMinute(i32::MIN), UnixMinute(2629500), MetaZone::Africa_FarWestern),
    (Tz::Africa__Bissau, UnixMinute(2629500), UnixMinute(i32::MAX), MetaZone::GMT),
    (Tz::Africa__Blantyre, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Africa_Central),
    (Tz::Africa__Brazzaville, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Africa_Western),
    (Tz::Africa__Bujumbura, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Africa_Central),
    (Tz::Africa__Cairo, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Eastern),
    (Tz::Africa__Casablanca, UnixMinute(i32::MIN), UnixMinute(7470720), MetaZone::Europe_Western),
    (Tz::Africa__Casablanca, UnixMinute(7470720), UnixMinute(8415300), MetaZone::Europe_Central),
    (Tz::Africa__Casablanca, UnixMinute(8415300), UnixMinute(i32::MAX), MetaZone::Europe_Western),
    (Tz::Africa__Ceuta, UnixMinute(i32::MIN), UnixMinute(7470720), MetaZone::Europe_Western),
    (Tz::Africa__Ceuta, UnixMinute(7470720), UnixMinute(i32::MAX), MetaZone::Europe_Central),
    (Tz::Africa__Conakry, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::GMT),
    (Tz::Africa__Dakar, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::GMT),
    (Tz::Africa__Dar_es_Salaam, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Africa_Eastern),
    (Tz::Africa__Djibouti, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Africa_Eastern),
    (Tz::Africa__Douala, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Africa_Western),
    (Tz::Africa__El_Aaiun, UnixMinute(i32::MIN), UnixMinute(3304860), MetaZone::Africa_FarWestern),
    (Tz::Africa__El_Aaiun, UnixMinute(3304860), UnixMinute(i32::MAX), MetaZone::Europe_Western),
    (Tz::Africa__Freetown, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::GMT),
    (Tz::Africa__Gaborone, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Africa_Central),
    (Tz::Africa__Harare, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Africa_Central),
    (Tz::Africa__Johannesburg, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Africa_Southern),
    (Tz::Africa__Juba, UnixMinute(i32::MIN), UnixMinute(15798840), MetaZone::Africa_Central),
    (Tz::Africa__Juba, UnixMinute(15798840), UnixMinute(i32::MAX), MetaZone::Africa_Eastern),
    (Tz::Africa__Kampala, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Africa_Eastern),
    (Tz::Africa__Khartoum, UnixMinute(i32::MIN), UnixMinute(15798840), MetaZone::Africa_Central),
    (Tz::Africa__Khartoum, UnixMinute(15798840), UnixMinute(i32::MAX), MetaZone::Africa_Eastern),
    (Tz::Africa__Kigali, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Africa_Central),
    (Tz::Africa__Kinshasa, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Africa_Western),
    (Tz::Africa__Lagos, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Africa_Western),
    (Tz::Africa__Libreville, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Africa_Western),
    (Tz::Africa__Lome, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::GMT),
    (Tz::Africa__Luanda, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Africa_Western),
    (Tz::Africa__Lubumbashi, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Africa_Central),
    (Tz::Africa__Lusaka, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Africa_Central),
    (Tz::Africa__Malabo, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Africa_Western),
    (Tz::Africa__Maputo, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Africa_Central),
    (Tz::Africa__Maseru, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Africa_Southern),
    (Tz::Africa__Mbabane, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Africa_Southern),
    (Tz::Africa__Mogadishu, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Africa_Eastern),
    (Tz::Africa__Monrovia, UnixMinute(i32::MIN), UnixMinute(1225485), MetaZone::Liberia),
    (Tz::Africa__Monrovia, UnixMinute(1225485), UnixMinute(i32::MAX), MetaZone::GMT),
    (Tz::Africa__Nairobi, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Africa_Eastern),
    (Tz::Africa__Ndjamena, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Africa_Western),
    (Tz::Africa__Niamey, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Africa_Western),
    (Tz::Africa__Nouakchott, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::GMT),
    (Tz::Africa__Ouagadougou, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::GMT),
    (Tz::Africa__PortoNovo, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Africa_Western),
    (Tz::Africa__Sao_Tome, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::GMT),
    (Tz::Africa__Tripoli, UnixMinute(i32::MIN), UnixMinute(6311400), MetaZone::Europe_Eastern),
    (Tz::Africa__Tripoli, UnixMinute(6311400), UnixMinute(10696260), MetaZone::Europe_Central),
    (Tz::Africa__Tripoli, UnixMinute(10696260), UnixMinute(14067240), MetaZone::Europe_Eastern),
    (Tz::Africa__Tripoli, UnixMinute(14067240), UnixMinute(14598600), MetaZone::Europe_Central),
    (Tz::Africa__Tripoli, UnixMinute(14598600), UnixMinute(22541760), MetaZone::Europe_Eastern),
    (Tz::Africa__Tripoli, UnixMinute(22541760), UnixMinute(23044320), MetaZone::Europe_Central),
    (Tz::Africa__Tripoli, UnixMinute(23044320), UnixMinute(i32::MAX), MetaZone::Europe_Eastern),
    (Tz::Africa__Tunis, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Central),
    (Tz::Africa__Windhoek, UnixMinute(i32::MIN), UnixMinute(10632840), MetaZone::Africa_Southern),
    (Tz::Africa__Windhoek, UnixMinute(10632840), UnixMinute(12755400), MetaZone::Africa_Central),
    (Tz::Africa__Windhoek, UnixMinute(12755400), UnixMinute(i32::MAX), MetaZone::Africa_Western),
    (Tz::America__Adak, UnixMinute(i32::MIN), UnixMinute(7272720), MetaZone::Bering),
    (Tz::America__Adak, UnixMinute(7272720), UnixMinute(7317240), MetaZone::Unknown),
    (Tz::America__Adak, UnixMinute(7317240), UnixMinute(i32::MAX), MetaZone::Hawaii_Aleutian),
    (Tz::America__Anchorage, UnixMinute(i32::MIN), UnixMinute(7272660), MetaZone::Alaska_Hawaii),
    (Tz::America__Anchorage, UnixMinute(7272660), UnixMinute(7317180), MetaZone::Yukon),
    (Tz::America__Anchorage, UnixMinute(7317180), UnixMinute(i32::MAX), MetaZone::Alaska),
    (Tz::America__Anguilla, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Atlantic),
    (Tz::America__Antigua, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Atlantic),
    (Tz::America__Araguaina, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Brasilia),
    (Tz::America__Argentina__La_Rioja, UnixMinute(i32::MIN), UnixMinute(11129880), MetaZone::Argentina),
    (Tz::America__Argentina__La_Rioja, UnixMinute(11129880), UnixMinute(11226480), MetaZone::Argentina_Western),
    (Tz::America__Argentina__La_Rioja, UnixMinute(11226480), UnixMinute(18100980), MetaZone::Argentina),
    (Tz::America__Argentina__La_Rioja, UnixMinute(18100980), UnixMinute(18128400), MetaZone::Argentina_Western),
    (Tz::America__Argentina__La_Rioja, UnixMinute(18128400), UnixMinute(i32::MAX), MetaZone::Argentina),
    (Tz::America__Argentina__Rio_Gallegos, UnixMinute(i32::MIN), UnixMinute(18100980), MetaZone::Argentina),
    (Tz::America__Argentina__Rio_Gallegos, UnixMinute(18100980), UnixMinute(18128400), MetaZone::Argentina_Western),
    (Tz::America__Argentina__Rio_Gallegos, UnixMinute(18128400), UnixMinute(i32::MAX), MetaZone::Argentina),
    (Tz::America__Argentina__Salta, UnixMinute(i32::MIN), UnixMinute(11132760), MetaZone::Argentina),
    (Tz::America__Argentina__Salta, UnixMinute(11132760), UnixMinute(11465520), MetaZone::Unknown),
    (Tz::America__Argentina__Salta, UnixMinute(11465520), UnixMinute(i32::MAX), MetaZone::Argentina),
    (Tz::America__Argentina__San_Juan, UnixMinute(i32::MIN), UnixMinute(11129880), MetaZone::Argentina),
    (Tz::America__Argentina__San_Juan, UnixMinute(11129880), UnixMinute(11226480), MetaZone::Argentina_Western),
    (Tz::America__Argentina__San_Juan, UnixMinute(11226480), UnixMinute(18099540), MetaZone::Argentina),
    (Tz::America__Argentina__San_Juan, UnixMinute(18099540), UnixMinute(18178800), MetaZone::Argentina_Western),
    (Tz::America__Argentina__San_Juan, UnixMinute(18178800), UnixMinute(i32::MAX), MetaZone::Argentina),
    (Tz::America__Argentina__San_Luis, UnixMinute(i32::MIN), UnixMinute(10623000), MetaZone::Argentina),
    (Tz::America__Argentina__San_Luis, UnixMinute(10623000), UnixMinute(11262480), MetaZone::Argentina_Western),
    (Tz::America__Argentina__San_Luis, UnixMinute(11262480), UnixMinute(15648660), MetaZone::Argentina),
    (Tz::America__Argentina__San_Luis, UnixMinute(15648660), UnixMinute(15867540), MetaZone::Argentina_Western),
    (Tz::America__Argentina__San_Luis, UnixMinute(15867540), UnixMinute(18099540), MetaZone::Argentina),
    (Tz::America__Argentina__San_Luis, UnixMinute(18099540), UnixMinute(18178800), MetaZone::Argentina_Western),
    (Tz::America__Argentina__San_Luis, UnixMinute(18178800), UnixMinute(20014680), MetaZone::Argentina),
    (Tz::America__Argentina__San_Luis, UnixMinute(20014680), UnixMinute(i32::MAX), MetaZone::Argentina_Western),
    (Tz::America__Argentina__Tucuman, UnixMinute(i32::MIN), UnixMinute(11132760), MetaZone::Argentina),
    (Tz::America__Argentina__Tucuman, UnixMinute(11132760), UnixMinute(11465520), MetaZone::Unknown),
    (Tz::America__Argentina__Tucuman, UnixMinute(11465520), UnixMinute(18100980), MetaZone::Argentina),
    (Tz::America__Argentina__Tucuman, UnixMinute(18100980), UnixMinute(18118320), MetaZone::Argentina_Western),
    (Tz::America__Argentina__Tucuman, UnixMinute(18118320), UnixMinute(i32::MAX), MetaZone::Argentina),
    (Tz::America__Argentina__Ushuaia, UnixMinute(i32::MIN), UnixMinute(18098100), MetaZone::Argentina),
    (Tz::America__Argentina__Ushuaia, UnixMinute(18098100), UnixMinute(18128400), MetaZone::Unknown),
    (Tz::America__Argentina__Ushuaia, UnixMinute(18128400), UnixMinute(i32::MAX), MetaZone::Argentina),
    (Tz::America__Aruba, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Atlantic),
    (Tz::America__Asuncion, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Paraguay),
    (Tz::America__Bahia, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Brasilia),
    (Tz::America__Bahia_Banderas, UnixMinute(i32::MIN), UnixMinute(480), MetaZone::America_Pacific),
    (Tz::America__Bahia_Banderas, UnixMinute(480), UnixMinute(21172860), MetaZone::America_Mountain),
    (Tz::America__Bahia_Banderas, UnixMinute(21172860), UnixMinute(i32::MAX), MetaZone::America_Central),
    (Tz::America__Barbados, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Atlantic),
    (Tz::America__Belem, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Brasilia),
    (Tz::America__Belize, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Central),
    (Tz::America__BlancSablon, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Atlantic),
    (Tz::America__Boa_Vista, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Amazon),
    (Tz::America__Bogota, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Colombia),
    (Tz::America__Boise, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Mountain),
    (Tz::America__Buenos_Aires, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Argentina),
    (Tz::America__Cambridge_Bay, UnixMinute(i32::MIN), UnixMinute(15689280), MetaZone::America_Mountain),
    (Tz::America__Cambridge_Bay, UnixMinute(15689280), UnixMinute(16213380), MetaZone::America_Central),
    (Tz::America__Cambridge_Bay, UnixMinute(16213380), UnixMinute(16223340), MetaZone::America_Eastern),
    (Tz::America__Cambridge_Bay, UnixMinute(16223340), UnixMinute(16435260), MetaZone::America_Central),
    (Tz::America__Cambridge_Bay, UnixMinute(16435260), UnixMinute(i32::MAX), MetaZone::America_Mountain),
    (Tz::America__Campo_Grande, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Amazon),
    (Tz::America__Cancun, UnixMinute(i32::MIN), UnixMinute(6298920), MetaZone::America_Central),
    (Tz::America__Cancun, UnixMinute(6298920), UnixMinute(15033960), MetaZone::America_Eastern),
    (Tz::America__Cancun, UnixMinute(15033960), UnixMinute(23712960), MetaZone::America_Central),
    (Tz::America__Cancun, UnixMinute(23712960), UnixMinute(i32::MAX), MetaZone::America_Eastern),
    (Tz::America__Caracas, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Venezuela),
    (Tz::America__Catamarca, UnixMinute(i32::MIN), UnixMinute(11132760), MetaZone::Argentina),
    (Tz::America__Catamarca, UnixMinute(11132760), UnixMinute(11465520), MetaZone::Unknown),
    (Tz::America__Catamarca, UnixMinute(11465520), UnixMinute(18100980), MetaZone::Argentina),
    (Tz::America__Catamarca, UnixMinute(18100980), UnixMinute(18128400), MetaZone::Argentina_Western),
    (Tz::America__Catamarca, UnixMinute(18128400), UnixMinute(i32::MAX), MetaZone::Argentina),
    (Tz::America__Cayenne, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::French_Guiana),
    (Tz::America__Cayman, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Eastern),
    (Tz::America__Chicago, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Central),
    (Tz::America__Chihuahua, UnixMinute(i32::MIN), UnixMinute(14862780), MetaZone::America_Central),
    (Tz::America__Chihuahua, UnixMinute(14862780), UnixMinute(i32::MAX), MetaZone::Mexico_Pacific),
    (Tz::America__Coral_Harbour, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Eastern),
    (Tz::America__Cordoba, UnixMinute(i32::MIN), UnixMinute(11132760), MetaZone::Argentina),
    (Tz::America__Cordoba, UnixMinute(11132760), UnixMinute(11465520), MetaZone::Unknown),
    (Tz::America__Cordoba, UnixMinute(11465520), UnixMinute(i32::MAX), MetaZone::Argentina),
    (Tz::America__Costa_Rica, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Central),
    (Tz::America__Creston, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Mountain),
    (Tz::America__Cuiaba, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Amazon),
    (Tz::America__Curacao, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Atlantic),
    (Tz::America__Danmarkshavn, UnixMinute(i32::MIN), UnixMinute(13674420), MetaZone::Greenland_Western),
    (Tz::America__Danmarkshavn, UnixMinute(13674420), UnixMinute(i32::MAX), MetaZone::GMT),
    (Tz::America__Dawson, UnixMinute(i32::MIN), UnixMinute(2010780), MetaZone::Yukon),
    (Tz::America__Dawson, UnixMinute(2010780), UnixMinute(i32::MAX), MetaZone::America_Pacific),
    (Tz::America__Dawson_Creek, UnixMinute(i32::MIN), UnixMinute(1400220), MetaZone::America_Pacific),
    (Tz::America__Dawson_Creek, UnixMinute(1400220), UnixMinute(i32::MAX), MetaZone::America_Mountain),
    (Tz::America__Denver, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Mountain),
    (Tz::America__Detroit, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Eastern),
    (Tz::America__Dominica, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Atlantic),
    (Tz::America__Edmonton, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Mountain),
    (Tz::America__Eirunepe, UnixMinute(i32::MIN), UnixMinute(20238060), MetaZone::Acre),
    (Tz::America__Eirunepe, UnixMinute(20238060), UnixMinute(23067600), MetaZone::Amazon),
    (Tz::America__Eirunepe, UnixMinute(23067600), UnixMinute(i32::MAX), MetaZone::Acre),
    (Tz::America__El_Salvador, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Central),
    (Tz::America__Fort_Nelson, UnixMinute(i32::MIN), UnixMinute(23763480), MetaZone::America_Pacific),
    (Tz::America__Fort_Nelson, UnixMinute(23763480), UnixMinute(i32::MAX), MetaZone::America_Mountain),
    (Tz::America__Fortaleza, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Brasilia),
    (Tz::America__Glace_Bay, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Atlantic),
    (Tz::America__Godthab, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Greenland_Western),
    (Tz::America__Goose_Bay, UnixMinute(i32::MIN), UnixMinute(9600721), MetaZone::Atlantic),
    (Tz::America__Goose_Bay, UnixMinute(9600721), UnixMinute(9903001), MetaZone::Goose_Bay),
    (Tz::America__Goose_Bay, UnixMinute(9903001), UnixMinute(i32::MAX), MetaZone::Atlantic),
    (Tz::America__Grand_Turk, UnixMinute(i32::MIN), UnixMinute(24105960), MetaZone::America_Eastern),
    (Tz::America__Grand_Turk, UnixMinute(24105960), UnixMinute(i32::MAX), MetaZone::Atlantic),
    (Tz::America__Grenada, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Atlantic),
    (Tz::America__Guadeloupe, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Atlantic),
    (Tz::America__Guatemala, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Central),
    (Tz::America__Guayaquil, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Ecuador),
    (Tz::America__Guyana, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Guyana),
    (Tz::America__Halifax, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Atlantic),
    (Tz::America__Havana, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Cuba),
    (Tz::America__Hermosillo, UnixMinute(i32::MIN), UnixMinute(480), MetaZone::America_Pacific),
    (Tz::America__Hermosillo, UnixMinute(480), UnixMinute(i32::MAX), MetaZone::Mexico_Pacific),
    (Tz::America__Indiana__Knox, UnixMinute(i32::MIN), UnixMinute(11475780), MetaZone::America_Central),
    (Tz::America__Indiana__Knox, UnixMinute(11475780), UnixMinute(19066020), MetaZone::America_Eastern),
    (Tz::America__Indiana__Knox, UnixMinute(19066020), UnixMinute(i32::MAX), MetaZone::America_Central),
    (Tz::America__Indiana__Marengo, UnixMinute(i32::MIN), UnixMinute(2111460), MetaZone::America_Eastern),
    (Tz::America__Indiana__Marengo, UnixMinute(2111460), UnixMinute(2534820), MetaZone::America_Central),
    (Tz::America__Indiana__Marengo, UnixMinute(2534820), UnixMinute(i32::MAX), MetaZone::America_Eastern),
    (Tz::America__Indiana__Petersburg, UnixMinute(i32::MIN), UnixMinute(4117380), MetaZone::America_Central),
    (Tz::America__Indiana__Petersburg, UnixMinute(4117380), UnixMinute(19066020), MetaZone::America_Eastern),
    (Tz::America__Indiana__Petersburg, UnixMinute(19066020), UnixMinute(19902660), MetaZone::America_Central),
    (Tz::America__Indiana__Petersburg, UnixMinute(19902660), UnixMinute(i32::MAX), MetaZone::America_Eastern),
    (Tz::America__Indiana__Tell_City, UnixMinute(i32::MIN), UnixMinute(19066020), MetaZone::America_Eastern),
    (Tz::America__Indiana__Tell_City, UnixMinute(19066020), UnixMinute(i32::MAX), MetaZone::America_Central),
    (Tz::America__Indiana__Vevay, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Eastern),
    (Tz::America__Indiana__Vincennes, UnixMinute(i32::MIN), UnixMinute(19066020), MetaZone::America_Eastern),
    (Tz::America__Indiana__Vincennes, UnixMinute(19066020), UnixMinute(19902660), MetaZone::America_Central),
    (Tz::America__Indiana__Vincennes, UnixMinute(19902660), UnixMinute(i32::MAX), MetaZone::America_Eastern),
    (Tz::America__Indiana__Winamac, UnixMinute(i32::MIN), UnixMinute(19066020), MetaZone::America_Eastern),
    (Tz::America__Indiana__Winamac, UnixMinute(19066020), UnixMinute(19560000), MetaZone::America_Central),
    (Tz::America__Indiana__Winamac, UnixMinute(19560000), UnixMinute(i32::MAX), MetaZone::America_Eastern),
    (Tz::America__Indianapolis, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Eastern),
    (Tz::America__Inuvik, UnixMinute(i32::MIN), UnixMinute(4903800), MetaZone::America_Pacific),
    (Tz::America__Inuvik, UnixMinute(4903800), UnixMinute(i32::MAX), MetaZone::America_Mountain),
    (Tz::America__Iqaluit, UnixMinute(i32::MIN), UnixMinute(15689160), MetaZone::America_Eastern),
    (Tz::America__Iqaluit, UnixMinute(15689160), UnixMinute(16213380), MetaZone::America_Central),
    (Tz::America__Iqaluit, UnixMinute(16213380), UnixMinute(i32::MAX), MetaZone::America_Eastern),
    (Tz::America__Jamaica, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Eastern),
    (Tz::America__Jujuy, UnixMinute(i32::MIN), UnixMinute(10608600), MetaZone::Argentina),
    (Tz::America__Jujuy, UnixMinute(10608600), UnixMinute(11445360), MetaZone::Unknown),
    (Tz::America__Jujuy, UnixMinute(11445360), UnixMinute(i32::MAX), MetaZone::Argentina),
    (Tz::America__Juneau, UnixMinute(i32::MIN), UnixMinute(5427960), MetaZone::America_Pacific),
    (Tz::America__Juneau, UnixMinute(5427960), UnixMinute(5690040), MetaZone::Yukon),
    (Tz::America__Juneau, UnixMinute(5690040), UnixMinute(7272540), MetaZone::America_Pacific),
    (Tz::America__Juneau, UnixMinute(7272540), UnixMinute(7317180), MetaZone::Yukon),
    (Tz::America__Juneau, UnixMinute(7317180), UnixMinute(i32::MAX), MetaZone::Alaska),
    (Tz::America__Kentucky__Monticello, UnixMinute(i32::MIN), UnixMinute(16213380), MetaZone::America_Central),
    (Tz::America__Kentucky__Monticello, UnixMinute(16213380), UnixMinute(i32::MAX), MetaZone::America_Eastern),
    (Tz::America__Kralendijk, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Atlantic),
    (Tz::America__La_Paz, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Bolivia),
    (Tz::America__Lima, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Peru),
    (Tz::America__Los_Angeles, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Pacific),
    (Tz::America__Louisville, UnixMinute(i32::MIN), UnixMinute(2111460), MetaZone::America_Eastern),
    (Tz::America__Louisville, UnixMinute(2111460), UnixMinute(2534820), MetaZone::America_Central),
    (Tz::America__Louisville, UnixMinute(2534820), UnixMinute(i32::MAX), MetaZone::America_Eastern),
    (Tz::America__Lower_Princes, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Atlantic),
    (Tz::America__Maceio, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Brasilia),
    (Tz::America__Managua, UnixMinute(i32::MIN), UnixMinute(1751400), MetaZone::America_Central),
    (Tz::America__Managua, UnixMinute(1751400), UnixMinute(2695980), MetaZone::America_Eastern),
    (Tz::America__Managua, UnixMinute(2695980), UnixMinute(11571000), MetaZone::America_Central),
    (Tz::America__Managua, UnixMinute(11571000), UnixMinute(11955180), MetaZone::America_Eastern),
    (Tz::America__Managua, UnixMinute(11955180), UnixMinute(12097800), MetaZone::America_Central),
    (Tz::America__Managua, UnixMinute(12097800), UnixMinute(14201580), MetaZone::America_Eastern),
    (Tz::America__Managua, UnixMinute(14201580), UnixMinute(i32::MAX), MetaZone::America_Central),
    (Tz::America__Manaus, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Amazon),
    (Tz::America__Marigot, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Atlantic),
    (Tz::America__Martinique, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Atlantic),
    (Tz::America__Matamoros, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Central),
    (Tz::America__Mazatlan, UnixMinute(i32::MIN), UnixMinute(480), MetaZone::America_Pacific),
    (Tz::America__Mazatlan, UnixMinute(480), UnixMinute(i32::MAX), MetaZone::Mexico_Pacific),
    (Tz::America__Mendoza, UnixMinute(i32::MIN), UnixMinute(10608600), MetaZone::Argentina),
    (Tz::America__Mendoza, UnixMinute(10608600), UnixMinute(11989680), MetaZone::Unknown),
    (Tz::America__Mendoza, UnixMinute(11989680), UnixMinute(18088020), MetaZone::Argentina),
    (Tz::America__Mendoza, UnixMinute(18088020), UnixMinute(18269520), MetaZone::Unknown),
    (Tz::America__Mendoza, UnixMinute(18269520), UnixMinute(i32::MAX), MetaZone::Argentina),
    (Tz::America__Menominee, UnixMinute(i32::MIN), UnixMinute(1748580), MetaZone::America_Eastern),
    (Tz::America__Menominee, UnixMinute(1748580), UnixMinute(i32::MAX), MetaZone::America_Central),
    (Tz::America__Merida, UnixMinute(i32::MIN), UnixMinute(6298920), MetaZone::America_Central),
    (Tz::America__Merida, UnixMinute(6298920), UnixMinute(6794220), MetaZone::America_Eastern),
    (Tz::America__Merida, UnixMinute(6794220), UnixMinute(i32::MAX), MetaZone::America_Central),
    (Tz::America__Metlakatla, UnixMinute(i32::MIN), UnixMinute(24106200), MetaZone::America_Pacific),
    (Tz::America__Metlakatla, UnixMinute(24106200), UnixMinute(i32::MAX), MetaZone::Alaska),
    (Tz::America__Mexico_City, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Central),
    (Tz::America__Miquelon, UnixMinute(i32::MIN), UnixMinute(5433360), MetaZone::Atlantic),
    (Tz::America__Miquelon, UnixMinute(5433360), UnixMinute(i32::MAX), MetaZone::Pierre_Miquelon),
    (Tz::America__Moncton, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Atlantic),
    (Tz::America__Monterrey, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Central),
    (Tz::America__Montevideo, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Uruguay),
    (Tz::America__Montserrat, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Atlantic),
    (Tz::America__Nassau, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Eastern),
    (Tz::America__New_York, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Eastern),
    (Tz::America__Nipigon, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Eastern),
    (Tz::America__Nome, UnixMinute(i32::MIN), UnixMinute(7272720), MetaZone::Bering),
    (Tz::America__Nome, UnixMinute(7272720), UnixMinute(7317180), MetaZone::Yukon),
    (Tz::America__Nome, UnixMinute(7317180), UnixMinute(i32::MAX), MetaZone::Alaska),
    (Tz::America__Noronha, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Noronha),
    (Tz::America__North_Dakota__Beulah, UnixMinute(i32::MIN), UnixMinute(21485280), MetaZone::America_Mountain),
    (Tz::America__North_Dakota__Beulah, UnixMinute(21485280), UnixMinute(i32::MAX), MetaZone::America_Central),
    (Tz::America__North_Dakota__Center, UnixMinute(i32::MIN), UnixMinute(12000000), MetaZone::America_Mountain),
    (Tz::America__North_Dakota__Center, UnixMinute(12000000), UnixMinute(i32::MAX), MetaZone::America_Central),
    (Tz::America__North_Dakota__New_Salem, UnixMinute(i32::MIN), UnixMinute(17785920), MetaZone::America_Mountain),
    (Tz::America__North_Dakota__New_Salem, UnixMinute(17785920), UnixMinute(i32::MAX), MetaZone::America_Central),
    (Tz::America__Ojinaga, UnixMinute(i32::MIN), UnixMinute(14862780), MetaZone::America_Central),
    (Tz::America__Ojinaga, UnixMinute(14862780), UnixMinute(i32::MAX), MetaZone::America_Mountain),
    (Tz::America__Panama, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Eastern),
    (Tz::America__Pangnirtung, UnixMinute(i32::MIN), UnixMinute(13280040), MetaZone::Atlantic),
    (Tz::America__Pangnirtung, UnixMinute(13280040), UnixMinute(15689160), MetaZone::America_Eastern),
    (Tz::America__Pangnirtung, UnixMinute(15689160), UnixMinute(16213380), MetaZone::America_Central),
    (Tz::America__Pangnirtung, UnixMinute(16213380), UnixMinute(i32::MAX), MetaZone::America_Eastern),
    (Tz::America__Paramaribo, UnixMinute(i32::MIN), UnixMinute(3094770), MetaZone::Dutch_Guiana),
    (Tz::America__Paramaribo, UnixMinute(3094770), UnixMinute(i32::MAX), MetaZone::Suriname),
    (Tz::America__Phoenix, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Mountain),
    (Tz::America__Port_of_Spain, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Atlantic),
    (Tz::America__PortauPrince, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Eastern),
    (Tz::America__Porto_Velho, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Amazon),
    (Tz::America__Puerto_Rico, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Atlantic),
    (Tz::America__Punta_Arenas, UnixMinute(i32::MIN), UnixMinute(24680100), MetaZone::Chile),
    (Tz::America__Punta_Arenas, UnixMinute(24680100), UnixMinute(i32::MAX), MetaZone::Unknown),
    (Tz::America__Rainy_River, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Central),
    (Tz::America__Rankin_Inlet, UnixMinute(i32::MIN), UnixMinute(16213380), MetaZone::America_Central),
    (Tz::America__Rankin_Inlet, UnixMinute(16213380), UnixMinute(16435200), MetaZone::America_Eastern),
    (Tz::America__Rankin_Inlet, UnixMinute(16435200), UnixMinute(i32::MAX), MetaZone::America_Central),
    (Tz::America__Recife, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Brasilia),
    (Tz::America__Regina, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Central),
    (Tz::America__Resolute, UnixMinute(i32::MIN), UnixMinute(16213380), MetaZone::America_Central),
    (Tz::America__Resolute, UnixMinute(16213380), UnixMinute(16435200), MetaZone::America_Eastern),
    (Tz::America__Resolute, UnixMinute(16435200), UnixMinute(19368420), MetaZone::America_Central),
    (Tz::America__Resolute, UnixMinute(19368420), UnixMinute(19560000), MetaZone::America_Eastern),
    (Tz::America__Resolute, UnixMinute(19560000), UnixMinute(i32::MAX), MetaZone::America_Central),
    (Tz::America__Rio_Branco, UnixMinute(i32::MIN), UnixMinute(20238060), MetaZone::Acre),
    (Tz::America__Rio_Branco, UnixMinute(20238060), UnixMinute(23067600), MetaZone::Amazon),
    (Tz::America__Rio_Branco, UnixMinute(23067600), UnixMinute(i32::MAX), MetaZone::Acre),
    (Tz::America__Santa_Isabel, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Mexico_Northwest),
    (Tz::America__Santarem, UnixMinute(i32::MIN), UnixMinute(20238000), MetaZone::Amazon),
    (Tz::America__Santarem, UnixMinute(20238000), UnixMinute(i32::MAX), MetaZone::Brasilia),
    (Tz::America__Santiago, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Chile),
    (Tz::America__Santo_Domingo, UnixMinute(i32::MIN), UnixMinute(2534700), MetaZone::Dominican),
    (Tz::America__Santo_Domingo, UnixMinute(2534700), UnixMinute(16213320), MetaZone::Atlantic),
    (Tz::America__Santo_Domingo, UnixMinute(16213320), UnixMinute(16263720), MetaZone::America_Eastern),
    (Tz::America__Santo_Domingo, UnixMinute(16263720), UnixMinute(i32::MAX), MetaZone::Atlantic),
    (Tz::America__Sao_Paulo, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Brasilia),
    (Tz::America__Scoresbysund, UnixMinute(i32::MIN), UnixMinute(5911320), MetaZone::Greenland_Central),
    (Tz::America__Scoresbysund, UnixMinute(5911320), UnixMinute(i32::MAX), MetaZone::Greenland_Eastern),
    (Tz::America__Sitka, UnixMinute(i32::MIN), UnixMinute(7272540), MetaZone::America_Pacific),
    (Tz::America__Sitka, UnixMinute(7272540), UnixMinute(7317180), MetaZone::Yukon),
    (Tz::America__Sitka, UnixMinute(7317180), UnixMinute(i32::MAX), MetaZone::Alaska),
    (Tz::America__St_Barthelemy, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Atlantic),
    (Tz::America__St_Johns, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Newfoundland),
    (Tz::America__St_Kitts, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Atlantic),
    (Tz::America__St_Lucia, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Atlantic),
    (Tz::America__St_Thomas, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Atlantic),
    (Tz::America__St_Vincent, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Atlantic),
    (Tz::America__Swift_Current, UnixMinute(i32::MIN), UnixMinute(1224540), MetaZone::America_Mountain),
    (Tz::America__Swift_Current, UnixMinute(1224540), UnixMinute(i32::MAX), MetaZone::America_Central),
    (Tz::America__Tegucigalpa, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Central),
    (Tz::America__Thule, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Atlantic),
    (Tz::America__Thunder_Bay, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Eastern),
    (Tz::America__Tijuana, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Pacific),
    (Tz::America__Toronto, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Eastern),
    (Tz::America__Tortola, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Atlantic),
    (Tz::America__Vancouver, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Pacific),
    (Tz::America__Whitehorse, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Pacific),
    (Tz::America__Winnipeg, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Central),
    (Tz::America__Yakutat, UnixMinute(i32::MIN), UnixMinute(7317180), MetaZone::Yukon),
    (Tz::America__Yakutat, UnixMinute(7317180), UnixMinute(i32::MAX), MetaZone::Alaska),
    (Tz::America__Yellowknife, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Mountain),
    (Tz::Antarctica__Casey, UnixMinute(i32::MIN), UnixMinute(20930040), MetaZone::Australia_Western),
    (Tz::Antarctica__Casey, UnixMinute(20930040), UnixMinute(21128580), MetaZone::Casey),
    (Tz::Antarctica__Casey, UnixMinute(21128580), UnixMinute(21995640), MetaZone::Australia_Western),
    (Tz::Antarctica__Casey, UnixMinute(21995640), UnixMinute(22164060), MetaZone::Casey),
    (Tz::Antarctica__Casey, UnixMinute(22164060), UnixMinute(24617760), MetaZone::Australia_Western),
    (Tz::Antarctica__Casey, UnixMinute(24617760), UnixMinute(i32::MAX), MetaZone::Casey),
    (Tz::Antarctica__Davis, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Davis),
    (Tz::Antarctica__DumontDUrville, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::DumontDUrville),
    (Tz::Antarctica__Macquarie, UnixMinute(i32::MIN), UnixMinute(21171840), MetaZone::Australia_Eastern),
    (Tz::Antarctica__Macquarie, UnixMinute(21171840), UnixMinute(i32::MAX), MetaZone::Macquarie),
    (Tz::Antarctica__Mawson, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Mawson),
    (Tz::Antarctica__McMurdo, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::New_Zealand),
    (Tz::Antarctica__Palmer, UnixMinute(i32::MIN), UnixMinute(6484500), MetaZone::Argentina),
    (Tz::Antarctica__Palmer, UnixMinute(6484500), UnixMinute(24680100), MetaZone::Chile),
    (Tz::Antarctica__Palmer, UnixMinute(24680100), UnixMinute(i32::MAX), MetaZone::Unknown),
    (Tz::Antarctica__Rothera, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Rothera),
    (Tz::Antarctica__Syowa, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Syowa),
    (Tz::Antarctica__Troll, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::GMT),
    (Tz::Antarctica__Vostok, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Vostok),
    (Tz::Arctic__Longyearbyen, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Central),
    (Tz::Asia__Aden, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Arabian),
    (Tz::Asia__Almaty, UnixMinute(i32::MIN), UnixMinute(18319440), MetaZone::Almaty),
    (Tz::Asia__Almaty, UnixMinute(18319440), UnixMinute(i32::MAX), MetaZone::Kazakhstan_Eastern),
    (Tz::Asia__Amman, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Eastern),
    (Tz::Asia__Anadyr, UnixMinute(i32::MIN), UnixMinute(21161640), MetaZone::Anadyr),
    (Tz::Asia__Anadyr, UnixMinute(21161640), UnixMinute(23570760), MetaZone::Magadan),
    (Tz::Asia__Anadyr, UnixMinute(23570760), UnixMinute(i32::MAX), MetaZone::Anadyr),
    (Tz::Asia__Aqtau, UnixMinute(i32::MIN), UnixMinute(11547060), MetaZone::Shevchenko),
    (Tz::Asia__Aqtau, UnixMinute(11547060), UnixMinute(18319560), MetaZone::Aqtau),
    (Tz::Asia__Aqtau, UnixMinute(18319560), UnixMinute(i32::MAX), MetaZone::Kazakhstan_Western),
    (Tz::Asia__Aqtobe, UnixMinute(i32::MIN), UnixMinute(11547060), MetaZone::Aktyubinsk),
    (Tz::Asia__Aqtobe, UnixMinute(11547060), UnixMinute(18319500), MetaZone::Aqtobe),
    (Tz::Asia__Aqtobe, UnixMinute(18319500), UnixMinute(18845100), MetaZone::Unknown),
    (Tz::Asia__Aqtobe, UnixMinute(18845100), UnixMinute(i32::MAX), MetaZone::Kazakhstan_Western),
    (Tz::Asia__Ashgabat, UnixMinute(i32::MIN), UnixMinute(11475120), MetaZone::Ashkhabad),
    (Tz::Asia__Ashgabat, UnixMinute(11475120), UnixMinute(i32::MAX), MetaZone::Turkmenistan),
    (Tz::Asia__Atyrau, UnixMinute(18319560), UnixMinute(i32::MAX), MetaZone::Kazakhstan_Western),
    (Tz::Asia__Baghdad, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Arabian),
    (Tz::Asia__Bahrain, UnixMinute(i32::MIN), UnixMinute(1269840), MetaZone::Gulf),
    (Tz::Asia__Bahrain, UnixMinute(1269840), UnixMinute(i32::MAX), MetaZone::Arabian),
    (Tz::Asia__Baku, UnixMinute(i32::MIN), UnixMinute(11391600), MetaZone::Baku),
    (Tz::Asia__Baku, UnixMinute(11391600), UnixMinute(i32::MAX), MetaZone::Azerbaijan),
    (Tz::Asia__Bangkok, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Indochina),
    (Tz::Asia__Beirut, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Eastern),
    (Tz::Asia__Bishkek, UnixMinute(i32::MIN), UnixMinute(11393040), MetaZone::Frunze),
    (Tz::Asia__Bishkek, UnixMinute(11393040), UnixMinute(i32::MAX), MetaZone::Kyrgystan),
    (Tz::Asia__Brunei, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Brunei),
    (Tz::Asia__Calcutta, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::India),
    (Tz::Asia__Chita, UnixMinute(i32::MIN), UnixMinute(23570880), MetaZone::Yakutsk),
    (Tz::Asia__Chita, UnixMinute(23570880), UnixMinute(24316920), MetaZone::Irkutsk),
    (Tz::Asia__Chita, UnixMinute(24316920), UnixMinute(i32::MAX), MetaZone::Yakutsk),
    (Tz::Asia__Choibalsan, UnixMinute(i32::MIN), UnixMinute(6966240), MetaZone::Mongolia),
    (Tz::Asia__Choibalsan, UnixMinute(6966240), UnixMinute(i32::MAX), MetaZone::Choibalsan),
    (Tz::Asia__Colombo, UnixMinute(i32::MIN), UnixMinute(13882710), MetaZone::India),
    (Tz::Asia__Colombo, UnixMinute(13882710), UnixMinute(19083990), MetaZone::Lanka),
    (Tz::Asia__Colombo, UnixMinute(19083990), UnixMinute(i32::MAX), MetaZone::India),
    (Tz::Asia__Damascus, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Eastern),
    (Tz::Asia__Dhaka, UnixMinute(i32::MIN), UnixMinute(646200), MetaZone::Dacca),
    (Tz::Asia__Dhaka, UnixMinute(646200), UnixMinute(i32::MAX), MetaZone::Bangladesh),
    (Tz::Asia__Dili, UnixMinute(i32::MIN), UnixMinute(3331620), MetaZone::East_Timor),
    (Tz::Asia__Dili, UnixMinute(3331620), UnixMinute(16152000), MetaZone::Indonesia_Central),
    (Tz::Asia__Dili, UnixMinute(16152000), UnixMinute(i32::MAX), MetaZone::East_Timor),
    (Tz::Asia__Dubai, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Gulf),
    (Tz::Asia__Dushanbe, UnixMinute(i32::MIN), UnixMinute(11406060), MetaZone::Dushanbe),
    (Tz::Asia__Dushanbe, UnixMinute(11406060), UnixMinute(i32::MAX), MetaZone::Tajikistan),
    (Tz::Asia__Famagusta, UnixMinute(i32::MIN), UnixMinute(24554700), MetaZone::Europe_Eastern),
    (Tz::Asia__Famagusta, UnixMinute(24554700), UnixMinute(i32::MAX), MetaZone::Unknown),
    (Tz::Asia__Gaza, UnixMinute(i32::MIN), UnixMinute(13674120), MetaZone::Israel),
    (Tz::Asia__Gaza, UnixMinute(13674120), UnixMinute(i32::MAX), MetaZone::Europe_Eastern),
    (Tz::Asia__Hebron, UnixMinute(i32::MIN), UnixMinute(13674120), MetaZone::Israel),
    (Tz::Asia__Hebron, UnixMinute(13674120), UnixMinute(i32::MAX), MetaZone::Europe_Eastern),
    (Tz::Asia__Hong_Kong, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Hong_Kong),
    (Tz::Asia__Hovd, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Hovd),
    (Tz::Asia__Irkutsk, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Irkutsk),
    (Tz::Asia__Jakarta, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Indonesia_Western),
    (Tz::Asia__Jayapura, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Indonesia_Eastern),
    (Tz::Asia__Jerusalem, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Israel),
    (Tz::Asia__Kabul, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Afghanistan),
    (Tz::Asia__Kamchatka, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Kamchatka),
    (Tz::Asia__Karachi, UnixMinute(i32::MIN), UnixMinute(646260), MetaZone::Karachi),
    (Tz::Asia__Karachi, UnixMinute(646260), UnixMinute(i32::MAX), MetaZone::Pakistan),
    (Tz::Asia__Katmandu, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Nepal),
    (Tz::Asia__Khandyga, UnixMinute(i32::MIN), UnixMinute(17881380), MetaZone::Yakutsk),
    (Tz::Asia__Khandyga, UnixMinute(17881380), UnixMinute(21930540), MetaZone::Vladivostok),
    (Tz::Asia__Khandyga, UnixMinute(21930540), UnixMinute(i32::MAX), MetaZone::Yakutsk),
    (Tz::Asia__Krasnoyarsk, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Krasnoyarsk),
    (Tz::Asia__Kuala_Lumpur, UnixMinute(i32::MIN), UnixMinute(6311070), MetaZone::Malaya),
    (Tz::Asia__Kuala_Lumpur, UnixMinute(6311070), UnixMinute(i32::MAX), MetaZone::Malaysia),
    (Tz::Asia__Kuching, UnixMinute(i32::MIN), UnixMinute(6311040), MetaZone::Borneo),
    (Tz::Asia__Kuching, UnixMinute(6311040), UnixMinute(i32::MAX), MetaZone::Malaysia),
    (Tz::Asia__Kuwait, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Arabian),
    (Tz::Asia__Macau, UnixMinute(i32::MIN), UnixMinute(15760320), MetaZone::Macau),
    (Tz::Asia__Macau, UnixMinute(15760320), UnixMinute(i32::MAX), MetaZone::China),
    (Tz::Asia__Magadan, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Magadan),
    (Tz::Asia__Makassar, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Indonesia_Central),
    (Tz::Asia__Manila, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Philippines),
    (Tz::Asia__Muscat, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Gulf),
    (Tz::Asia__Nicosia, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Eastern),
    (Tz::Asia__Novokuznetsk, UnixMinute(i32::MIN), UnixMinute(21161940), MetaZone::Krasnoyarsk),
    (Tz::Asia__Novokuznetsk, UnixMinute(21161940), UnixMinute(23571060), MetaZone::Novosibirsk),
    (Tz::Asia__Novokuznetsk, UnixMinute(23571060), UnixMinute(i32::MAX), MetaZone::Krasnoyarsk),
    (Tz::Asia__Novosibirsk, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Novosibirsk),
    (Tz::Asia__Omsk, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Omsk),
    (Tz::Asia__Oral, UnixMinute(i32::MIN), UnixMinute(11547120), MetaZone::Uralsk),
    (Tz::Asia__Oral, UnixMinute(11547120), UnixMinute(18319560), MetaZone::Oral),
    (Tz::Asia__Oral, UnixMinute(18319560), UnixMinute(i32::MAX), MetaZone::Kazakhstan_Western),
    (Tz::Asia__Phnom_Penh, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Indochina),
    (Tz::Asia__Pontianak, UnixMinute(i32::MIN), UnixMinute(9466080), MetaZone::Indonesia_Central),
    (Tz::Asia__Pontianak, UnixMinute(9466080), UnixMinute(i32::MAX), MetaZone::Indonesia_Western),
    (Tz::Asia__Pyongyang, UnixMinute(i32::MIN), UnixMinute(23992740), MetaZone::Korea),
    (Tz::Asia__Pyongyang, UnixMinute(23992740), UnixMinute(i32::MAX), MetaZone::Pyongyang),
    (Tz::Asia__Qatar, UnixMinute(i32::MIN), UnixMinute(1269840), MetaZone::Gulf),
    (Tz::Asia__Qatar, UnixMinute(1269840), UnixMinute(i32::MAX), MetaZone::Arabian),
    (Tz::Asia__Qyzylorda, UnixMinute(i32::MIN), UnixMinute(11547060), MetaZone::Kizilorda),
    (Tz::Asia__Qyzylorda, UnixMinute(11547060), UnixMinute(18319500), MetaZone::Qyzylorda),
    (Tz::Asia__Qyzylorda, UnixMinute(18319500), UnixMinute(i32::MAX), MetaZone::Kazakhstan_Eastern),
    (Tz::Asia__Rangoon, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Myanmar),
    (Tz::Asia__Riyadh, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Arabian),
    (Tz::Asia__Saigon, UnixMinute(2863680), UnixMinute(i32::MAX), MetaZone::Indochina),
    (Tz::Asia__Sakhalin, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Sakhalin),
    (Tz::Asia__Samarkand, UnixMinute(i32::MIN), UnixMinute(6178680), MetaZone::Samarkand),
    (Tz::Asia__Samarkand, UnixMinute(6178680), UnixMinute(6440760), MetaZone::Tashkent),
    (Tz::Asia__Samarkand, UnixMinute(6440760), UnixMinute(11394360), MetaZone::Samarkand),
    (Tz::Asia__Samarkand, UnixMinute(11394360), UnixMinute(i32::MAX), MetaZone::Uzbekistan),
    (Tz::Asia__Seoul, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Korea),
    (Tz::Asia__Shanghai, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::China),
    (Tz::Asia__Singapore, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Singapore),
    (Tz::Asia__Srednekolymsk, UnixMinute(i32::MIN), UnixMinute(23570760), MetaZone::Magadan),
    (Tz::Asia__Srednekolymsk, UnixMinute(23570760), UnixMinute(i32::MAX), MetaZone::Unknown),
    (Tz::Asia__Taipei, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Taipei),
    (Tz::Asia__Tashkent, UnixMinute(i32::MIN), UnixMinute(11394360), MetaZone::Tashkent),
    (Tz::Asia__Tashkent, UnixMinute(11394360), UnixMinute(i32::MAX), MetaZone::Uzbekistan),
    (Tz::Asia__Tbilisi, UnixMinute(i32::MIN), UnixMinute(11185680), MetaZone::Tbilisi),
    (Tz::Asia__Tbilisi, UnixMinute(11185680), UnixMinute(i32::MAX), MetaZone::Georgia),
    (Tz::Asia__Tehran, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Iran),
    (Tz::Asia__Thimphu, UnixMinute(i32::MIN), UnixMinute(9333750), MetaZone::India),
    (Tz::Asia__Thimphu, UnixMinute(9333750), UnixMinute(i32::MAX), MetaZone::Bhutan),
    (Tz::Asia__Tokyo, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Japan),
    (Tz::Asia__Ulaanbaatar, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Mongolia),
    (Tz::Asia__Urumqi, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Urumqi),
    (Tz::Asia__UstNera, UnixMinute(i32::MIN), UnixMinute(5914980), MetaZone::Yakutsk),
    (Tz::Asia__UstNera, UnixMinute(5914980), UnixMinute(21930480), MetaZone::Magadan),
    (Tz::Asia__UstNera, UnixMinute(21930480), UnixMinute(i32::MAX), MetaZone::Vladivostok),
    (Tz::Asia__Vientiane, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Indochina),
    (Tz::Asia__Vladivostok, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Vladivostok),
    (Tz::Asia__Yakutsk, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Yakutsk),
    (Tz::Asia__Yekaterinburg, UnixMinute(i32::MIN), UnixMinute(11596200), MetaZone::Sverdlovsk),
    (Tz::Asia__Yekaterinburg, UnixMinute(11596200), UnixMinute(i32::MAX), MetaZone::Yekaterinburg),
    (Tz::Asia__Yerevan, UnixMinute(i32::MIN), UnixMinute(11426160), MetaZone::Yerevan),
    (Tz::Asia__Yerevan, UnixMinute(11426160), UnixMinute(i32::MAX), MetaZone::Armenia),
    (Tz::Atlantic__Azores, UnixMinute(i32::MIN), UnixMinute(11959320), MetaZone::Azores),
    (Tz::Atlantic__Azores, UnixMinute(11959320), UnixMinute(12221340), MetaZone::Europe_Western),
    (Tz::Atlantic__Azores, UnixMinute(12221340), UnixMinute(i32::MAX), MetaZone::Azores),
    (Tz::Atlantic__Bermuda, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Atlantic),
    (Tz::Atlantic__Canary, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Western),
    (Tz::Atlantic__Cape_Verde, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Cape_Verde),
    (Tz::Atlantic__Faeroe, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Western),
    (Tz::Atlantic__Madeira, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Western),
    (Tz::Atlantic__Reykjavik, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::GMT),
    (Tz::Atlantic__South_Georgia, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::South_Georgia),
    (Tz::Atlantic__St_Helena, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::GMT),
    (Tz::Atlantic__Stanley, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Falkland),
    (Tz::Australia__Adelaide, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Australia_Central),
    (Tz::Australia__Brisbane, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Australia_Eastern),
    (Tz::Australia__Broken_Hill, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Australia_Central),
    (Tz::Australia__Currie, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Australia_Eastern),
    (Tz::Australia__Darwin, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Australia_Central),
    (Tz::Australia__Eucla, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Australia_CentralWestern),
    (Tz::Australia__Hobart, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Australia_Eastern),
    (Tz::Australia__Lindeman, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Australia_Eastern),
    (Tz::Australia__Lord_Howe, UnixMinute(i32::MIN), UnixMinute(5870280), MetaZone::Australia_Eastern),
    (Tz::Australia__Lord_Howe, UnixMinute(5870280), UnixMinute(i32::MAX), MetaZone::Lord_Howe),
    (Tz::Australia__Melbourne, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Australia_Eastern),
    (Tz::Australia__Perth, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Australia_Western),
    (Tz::Australia__Sydney, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Australia_Eastern),
    (Tz::CST6CDT, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Central),
    (Tz::EST5EDT, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Eastern),
    (Tz::Etc__GMT, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::GMT),
    (Tz::Europe__Amsterdam, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Central),
    (Tz::Europe__Andorra, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Central),
    (Tz::Europe__Astrakhan, UnixMinute(11697000), UnixMinute(24317220), MetaZone::Moscow),
    (Tz::Europe__Astrakhan, UnixMinute(24317220), UnixMinute(i32::MAX), MetaZone::Unknown),
    (Tz::Europe__Athens, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Eastern),
    (Tz::Europe__Belgrade, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Central),
    (Tz::Europe__Berlin, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Central),
    (Tz::Europe__Bratislava, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Central),
    (Tz::Europe__Brussels, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Central),
    (Tz::Europe__Bucharest, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Eastern),
    (Tz::Europe__Budapest, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Central),
    (Tz::Europe__Busingen, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Central),
    (Tz::Europe__Chisinau, UnixMinute(i32::MIN), UnixMinute(10699020), MetaZone::Moscow),
    (Tz::Europe__Chisinau, UnixMinute(10699020), UnixMinute(i32::MAX), MetaZone::Europe_Eastern),
    (Tz::Europe__Copenhagen, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Central),
    (Tz::Europe__Dublin, UnixMinute(i32::MIN), UnixMinute(962040), MetaZone::Irish),
    (Tz::Europe__Dublin, UnixMinute(962040), UnixMinute(i32::MAX), MetaZone::GMT),
    (Tz::Europe__Gibraltar, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Central),
    (Tz::Europe__Guernsey, UnixMinute(i32::MIN), UnixMinute(962040), MetaZone::British),
    (Tz::Europe__Guernsey, UnixMinute(962040), UnixMinute(i32::MAX), MetaZone::GMT),
    (Tz::Europe__Helsinki, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Eastern),
    (Tz::Europe__Isle_of_Man, UnixMinute(i32::MIN), UnixMinute(962040), MetaZone::British),
    (Tz::Europe__Isle_of_Man, UnixMinute(962040), UnixMinute(i32::MAX), MetaZone::GMT),
    (Tz::Europe__Istanbul, UnixMinute(i32::MIN), UnixMinute(4620780), MetaZone::Europe_Eastern),
    (Tz::Europe__Istanbul, UnixMinute(4620780), UnixMinute(8046540), MetaZone::Turkey),
    (Tz::Europe__Istanbul, UnixMinute(8046540), UnixMinute(24553260), MetaZone::Europe_Eastern),
    (Tz::Europe__Istanbul, UnixMinute(24553260), UnixMinute(i32::MAX), MetaZone::Turkey),
    (Tz::Europe__Jersey, UnixMinute(i32::MIN), UnixMinute(962040), MetaZone::British),
    (Tz::Europe__Jersey, UnixMinute(962040), UnixMinute(i32::MAX), MetaZone::GMT),
    (Tz::Europe__Kaliningrad, UnixMinute(i32::MIN), UnixMinute(10114500), MetaZone::Moscow),
    (Tz::Europe__Kaliningrad, UnixMinute(10114500), UnixMinute(21686400), MetaZone::Europe_Eastern),
    (Tz::Europe__Kaliningrad, UnixMinute(21686400), UnixMinute(23571300), MetaZone::Europe_Further_Eastern),
    (Tz::Europe__Kaliningrad, UnixMinute(23571300), UnixMinute(i32::MAX), MetaZone::Europe_Eastern),
    (Tz::Europe__Kiev, UnixMinute(i32::MIN), UnixMinute(10779720), MetaZone::Moscow),
    (Tz::Europe__Kiev, UnixMinute(10779720), UnixMinute(i32::MAX), MetaZone::Europe_Eastern),
    (Tz::Europe__Lisbon, UnixMinute(i32::MIN), UnixMinute(3542400), MetaZone::Europe_Central),
    (Tz::Europe__Lisbon, UnixMinute(3542400), UnixMinute(11959260), MetaZone::Europe_Western),
    (Tz::Europe__Lisbon, UnixMinute(11959260), UnixMinute(13803900), MetaZone::Europe_Central),
    (Tz::Europe__Lisbon, UnixMinute(13803900), UnixMinute(i32::MAX), MetaZone::Europe_Western),
    (Tz::Europe__Ljubljana, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Central),
    (Tz::Europe__London, UnixMinute(i32::MIN), UnixMinute(962040), MetaZone::British),
    (Tz::Europe__London, UnixMinute(962040), UnixMinute(i32::MAX), MetaZone::GMT),
    (Tz::Europe__Luxembourg, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Central),
    (Tz::Europe__Madrid, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Central),
    (Tz::Europe__Malta, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Central),
    (Tz::Europe__Mariehamn, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Eastern),
    (Tz::Europe__Minsk, UnixMinute(i32::MIN), UnixMinute(11172900), MetaZone::Moscow),
    (Tz::Europe__Minsk, UnixMinute(11172900), UnixMinute(21686400), MetaZone::Europe_Eastern),
    (Tz::Europe__Minsk, UnixMinute(21686400), UnixMinute(23572680), MetaZone::Europe_Further_Eastern),
    (Tz::Europe__Minsk, UnixMinute(23572680), UnixMinute(i32::MAX), MetaZone::Moscow),
    (Tz::Europe__Monaco, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Central),
    (Tz::Europe__Moscow, UnixMinute(i32::MIN), UnixMinute(11172900), MetaZone::Moscow),
    (Tz::Europe__Moscow, UnixMinute(11172900), UnixMinute(11596320), MetaZone::Europe_Eastern),
    (Tz::Europe__Moscow, UnixMinute(11596320), UnixMinute(i32::MAX), MetaZone::Moscow),
    (Tz::Europe__Oslo, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Central),
    (Tz::Europe__Paris, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Central),
    (Tz::Europe__Podgorica, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Central),
    (Tz::Europe__Prague, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Central),
    (Tz::Europe__Riga, UnixMinute(i32::MIN), UnixMinute(10114500), MetaZone::Moscow),
    (Tz::Europe__Riga, UnixMinute(10114500), UnixMinute(i32::MAX), MetaZone::Europe_Eastern),
    (Tz::Europe__Rome, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Central),
    (Tz::Europe__Samara, UnixMinute(i32::MIN), UnixMinute(10114440), MetaZone::Kuybyshev),
    (Tz::Europe__Samara, UnixMinute(10114440), UnixMinute(11172900), MetaZone::Moscow),
    (Tz::Europe__Samara, UnixMinute(11172900), UnixMinute(11435040), MetaZone::Europe_Eastern),
    (Tz::Europe__Samara, UnixMinute(11435040), UnixMinute(i32::MAX), MetaZone::Samara),
    (Tz::Europe__San_Marino, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Central),
    (Tz::Europe__Sarajevo, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Central),
    (Tz::Europe__Saratov, UnixMinute(11697000), UnixMinute(24680100), MetaZone::Moscow),
    (Tz::Europe__Saratov, UnixMinute(24680100), UnixMinute(i32::MAX), MetaZone::Unknown),
    (Tz::Europe__Simferopol, UnixMinute(i32::MIN), UnixMinute(10779780), MetaZone::Moscow),
    (Tz::Europe__Simferopol, UnixMinute(10779780), UnixMinute(12795660), MetaZone::Europe_Eastern),
    (Tz::Europe__Simferopol, UnixMinute(12795660), UnixMinute(14328060), MetaZone::Moscow),
    (Tz::Europe__Simferopol, UnixMinute(14328060), UnixMinute(23268960), MetaZone::Europe_Eastern),
    (Tz::Europe__Simferopol, UnixMinute(23268960), UnixMinute(i32::MAX), MetaZone::Moscow),
    (Tz::Europe__Skopje, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Central),
    (Tz::Europe__Sofia, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Eastern),
    (Tz::Europe__Stockholm, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Central),
    (Tz::Europe__Tallinn, UnixMinute(i32::MIN), UnixMinute(10114500), MetaZone::Moscow),
    (Tz::Europe__Tallinn, UnixMinute(10114500), UnixMinute(i32::MAX), MetaZone::Europe_Eastern),
    (Tz::Europe__Tirane, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Central),
    (Tz::Europe__Ulyanovsk, UnixMinute(11596320), UnixMinute(24317220), MetaZone::Moscow),
    (Tz::Europe__Ulyanovsk, UnixMinute(24317220), UnixMinute(i32::MAX), MetaZone::Unknown),
    (Tz::Europe__Uzhgorod, UnixMinute(i32::MIN), UnixMinute(10779780), MetaZone::Moscow),
    (Tz::Europe__Uzhgorod, UnixMinute(10779780), UnixMinute(11173080), MetaZone::Europe_Central),
    (Tz::Europe__Uzhgorod, UnixMinute(11173080), UnixMinute(i32::MAX), MetaZone::Europe_Eastern),
    (Tz::Europe__Vaduz, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Central),
    (Tz::Europe__Vatican, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Central),
    (Tz::Europe__Vienna, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Central),
    (Tz::Europe__Vilnius, UnixMinute(i32::MIN), UnixMinute(10114500), MetaZone::Moscow),
    (Tz::Europe__Vilnius, UnixMinute(10114500), UnixMinute(14852220), MetaZone::Europe_Eastern),
    (Tz::Europe__Vilnius, UnixMinute(14852220), UnixMinute(15688860), MetaZone::Europe_Central),
    (Tz::Europe__Vilnius, UnixMinute(15688860), UnixMinute(i32::MAX), MetaZone::Europe_Eastern),
    (Tz::Europe__Volgograd, UnixMinute(i32::MIN), UnixMinute(11697000), MetaZone::Volgograd),
    (Tz::Europe__Volgograd, UnixMinute(11697000), UnixMinute(i32::MAX), MetaZone::Moscow),
    (Tz::Europe__Warsaw, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Central),
    (Tz::Europe__Zagreb, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Central),
    (Tz::Europe__Zaporozhye, UnixMinute(i32::MIN), UnixMinute(11172900), MetaZone::Moscow),
    (Tz::Europe__Zaporozhye, UnixMinute(11172900), UnixMinute(i32::MAX), MetaZone::Europe_Eastern),
    (Tz::Europe__Zurich, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Europe_Central),
    (Tz::Indian__Antananarivo, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Africa_Eastern),
    (Tz::Indian__Chagos, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Indian_Ocean),
    (Tz::Indian__Christmas, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Christmas),
    (Tz::Indian__Cocos, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Cocos),
    (Tz::Indian__Comoro, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Africa_Eastern),
    (Tz::Indian__Kerguelen, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::French_Southern),
    (Tz::Indian__Mahe, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Seychelles),
    (Tz::Indian__Maldives, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Maldives),
    (Tz::Indian__Mauritius, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Mauritius),
    (Tz::Indian__Mayotte, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Africa_Eastern),
    (Tz::Indian__Reunion, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Reunion),
    (Tz::MST7MDT, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Mountain),
    (Tz::PST8PDT, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::America_Pacific),
    (Tz::Pacific__Apia, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Apia),
    (Tz::Pacific__Auckland, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::New_Zealand),
    (Tz::Pacific__Bougainville, UnixMinute(i32::MIN), UnixMinute(23661600), MetaZone::Papua_New_Guinea),
    (Tz::Pacific__Bougainville, UnixMinute(23661600), UnixMinute(i32::MAX), MetaZone::Unknown),
    (Tz::Pacific__Chatham, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Chatham),
    (Tz::Pacific__Easter, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Easter),
    (Tz::Pacific__Efate, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Vanuatu),
    (Tz::Pacific__Enderbury, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Phoenix_Islands),
    (Tz::Pacific__Fakaofo, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Tokelau),
    (Tz::Pacific__Fiji, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Fiji),
    (Tz::Pacific__Funafuti, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Tuvalu),
    (Tz::Pacific__Galapagos, UnixMinute(i32::MIN), UnixMinute(8415660), MetaZone::Ecuador),
    (Tz::Pacific__Galapagos, UnixMinute(8415660), UnixMinute(i32::MAX), MetaZone::Galapagos),
    (Tz::Pacific__Gambier, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Gambier),
    (Tz::Pacific__Guadalcanal, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Solomon),
    (Tz::Pacific__Guam, UnixMinute(i32::MIN), UnixMinute(16291560), MetaZone::Guam),
    (Tz::Pacific__Guam, UnixMinute(16291560), UnixMinute(i32::MAX), MetaZone::Chamorro),
    (Tz::Pacific__Honolulu, UnixMinute(i32::MIN), UnixMinute(7272660), MetaZone::Alaska_Hawaii),
    (Tz::Pacific__Honolulu, UnixMinute(7272660), UnixMinute(i32::MAX), MetaZone::Hawaii_Aleutian),
    (Tz::Pacific__Johnston, UnixMinute(i32::MIN), UnixMinute(7272660), MetaZone::Alaska_Hawaii),
    (Tz::Pacific__Johnston, UnixMinute(7272660), UnixMinute(i32::MAX), MetaZone::Hawaii_Aleutian),
    (Tz::Pacific__Kiritimati, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Line_Islands),
    (Tz::Pacific__Kosrae, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Kosrae),
    (Tz::Pacific__Kwajalein, UnixMinute(i32::MIN), UnixMinute(12430800), MetaZone::Kwajalein),
    (Tz::Pacific__Kwajalein, UnixMinute(12430800), UnixMinute(i32::MAX), MetaZone::Marshall_Islands),
    (Tz::Pacific__Majuro, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Marshall_Islands),
    (Tz::Pacific__Marquesas, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Marquesas),
    (Tz::Pacific__Midway, UnixMinute(i32::MIN), UnixMinute(7272720), MetaZone::Bering),
    (Tz::Pacific__Midway, UnixMinute(7272720), UnixMinute(i32::MAX), MetaZone::Samoa),
    (Tz::Pacific__Nauru, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Nauru),
    (Tz::Pacific__Niue, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Niue),
    (Tz::Pacific__Norfolk, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Norfolk),
    (Tz::Pacific__Noumea, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::New_Caledonia),
    (Tz::Pacific__Pago_Pago, UnixMinute(i32::MIN), UnixMinute(7272720), MetaZone::Bering),
    (Tz::Pacific__Pago_Pago, UnixMinute(7272720), UnixMinute(i32::MAX), MetaZone::Samoa),
    (Tz::Pacific__Palau, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Palau),
    (Tz::Pacific__Pitcairn, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Pitcairn),
    (Tz::Pacific__Ponape, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Ponape),
    (Tz::Pacific__Port_Moresby, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Papua_New_Guinea),
    (Tz::Pacific__Rarotonga, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Cook),
    (Tz::Pacific__Saipan, UnixMinute(i32::MIN), UnixMinute(16291560), MetaZone::North_Mariana),
    (Tz::Pacific__Saipan, UnixMinute(16291560), UnixMinute(i32::MAX), MetaZone::Chamorro),
    (Tz::Pacific__Tahiti, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Tahiti),
    (Tz::Pacific__Tarawa, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Gilbert_Islands),
    (Tz::Pacific__Tongatapu, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Tonga),
    (Tz::Pacific__Truk, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Truk),
    (Tz::Pacific__Wake, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Wake),
    (Tz::Pacific__Wallis, UnixMinute(i32::MIN), UnixMinute(i32::MAX), MetaZone::Wallis),
];
